window.AUREA={wa:"94702128546",delivery:400,logo:"",hero:"",products:[
{id:"snail96",n:"Advanced Snail 96 Mucin Power Essence",c:"Hydrate",t:"tube",l:"SNAIL 96",price:4800,stock:12,size:"100 ml",skin:["All"],when:"Morning and night",d:"A lightweight, watery essence made of 96% snail secretion filtrate that hydrates, soothes and helps skin look repaired and bouncy.",ing:["Snail secretion filtrate (96.3%)","Betaine","Sodium hyaluronate"],ben:["Deep, lightweight hydration","Calms dry, tired skin","Soft, glassy finish"],use:"After cleansing and toner, pat 2 to 3 pumps into the face morning and night.",tip:"Great as your first hydrating step under cream."},
{id:"snail92",n:"Advanced Snail 92 All-in-One Cream",c:"Hydrate",t:"jar",l:"SNAIL 92",price:5200,stock:8,size:"100 g",skin:["All"],when:"Morning and night",d:"A soft gel-cream with 92% snail secretion filtrate that moisturises and nourishes in one step.",ing:["Snail secretion filtrate (92%)","Betaine","Allantoin"],ben:["Comfortable daily moisture","Smooths and softens","Suits dry and normal skin best"],use:"Apply a small amount as the last step of your night routine, or in the morning before SPF.",tip:"A little goes a long way."},
{id:"gelcl",n:"Low pH Good Morning Gel Cleanser",c:"Cleanse",t:"tube",l:"GEL CLEANSER",price:2900,stock:15,size:"150 ml",skin:["Oily","Combination","Sensitive"],when:"Morning (or night)",d:"A gentle, slightly acidic gel cleanser that matches skin's natural pH for a fresh, non-tight finish.",ing:["Tea tree leaf oil","Betaine salicylate (BHA)","Low pH formula (about 5 to 6)"],ben:["Removes oil and light dirt","Does not leave skin tight","Refreshing morning start"],use:"Massage onto damp skin, then rinse with lukewarm water.",tip:"Use a separate oil cleanser first if you wear makeup or sunscreen."},
{id:"salic",n:"Salicylic Acid Daily Gentle Cleanser",c:"Cleanse",t:"tube",l:"SALICYLIC",price:3100,stock:3,size:"150 ml",skin:["Oily","Combination"],when:"Morning or night",d:"A daily cleanser with salicylic acid that clears pores and helps keep breakouts in check without over-drying.",ing:["Salicylic acid (BHA)","Tea tree leaf oil","Low pH formula"],ben:["Unclogs pores","Helps with blackheads and oil","Gentle enough for daily use"],use:"Use once or twice daily on damp skin, then rinse well.",tip:"Start once a day if your skin is new to acids."},
{id:"bha",n:"BHA Blackhead Power Liquid",c:"Treat",t:"bottle",l:"BHA LIQUID",price:3600,stock:10,size:"100 ml",skin:["Oily","Combination"],when:"Night, 2 to 3 times a week",d:"A leave-on exfoliating liquid with 4% betaine salicylate that smooths texture and unclogs pores.",ing:["Betaine salicylate (4%)","Willow bark water","Niacinamide"],ben:["Reduces blackheads","Refines pores and texture","Less irritating than plain BHA"],use:"Apply with a cotton pad after cleansing, 2 to 3 nights a week. Use SPF in the morning.",tip:"Do not combine with AHA on the same night."},
{id:"aha",n:"AHA 7 Whitehead Power Liquid",c:"Treat",t:"bottle",l:"AHA 7",price:3600,stock:0,size:"50 ml",skin:["Normal","Combination","Dry"],when:"Night, 2 to 3 times a week",d:"A leave-on exfoliating liquid with 7% glycolic acid that brightens dull skin and smooths rough texture.",ing:["Glycolic acid (AHA, 7%)","Tea tree leaf oil","Allantoin"],ben:["Brightens dull skin","Smooths bumpy texture","Helps with whiteheads"],use:"Apply with a cotton pad at night, 2 to 3 times a week. Use SPF in the morning.",tip:"Skip if your skin is very sensitive or irritated."},
{id:"prop",n:"Full Fit Propolis Light Ampoule",c:"Hydrate",t:"drop",l:"PROPOLIS",price:4400,stock:6,size:"30 ml",skin:["Oily","Combination","Sensitive"],when:"Morning and night",d:"A light, glowy ampoule rich in propolis extract that nourishes and calms without feeling heavy.",ing:["Propolis extract (83%)","Sunflower seed oil","Panthenol"],ben:["Healthy-looking glow","Light nourishment","Soothes dull, stressed skin"],use:"Press a few drops into clean skin before moisturiser.",tip:"Avoid if you are allergic to bee products."},
{id:"sun",n:"Aloe Soothing Sun Cream SPF50+",c:"Protect",t:"tube",l:"ALOE SUN",price:3900,stock:9,size:"50 ml",skin:["All"],when:"Every morning",d:"A light, comfortable daily sunscreen with SPF50+ PA+++ and aloe to keep skin soothed outdoors.",ing:["Aloe leaf extract","SPF50+ PA+++ filters"],ben:["Broad daily sun protection","Light, non-greasy feel","Soothing aloe"],use:"Apply generously as the last morning step. Reapply every 2 hours when outdoors.",tip:"Use about two finger-lengths for the face and neck."}]};
